project:
  type: website

website:
  title: "Justin Gregoire - personal site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: resume.pdf
        text: Resume
    
format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true

editor: visual

